### ISSUE TITLE
make qemu - docker: failed to register layer: Error processing tar file(exit status 1): unexpected EOF.

### ISSUE THREAD

**Issue by Phi-Ho** [jjyr/jonesforth_riscv#3]
Greetings,

~/jonesforth_riscv$ uname -a
Linux ubuntu 4.14.130-ltsi #1 SMP Wed Aug 5 05:33:09 UTC 2020 armv7l armv7l armv7l GNU/Linux
~/jonesforth_riscv$

Please find appended below the console transcript.

Regards,

phiho

~/jonesforth_riscv$ sudo make qemu
docker run --name riscv-qemu-fedora -p 4321:10000 jjy0/riscv-qemu-fedora
Unable to find image 'jjy0/riscv-qemu-fedora:latest' locally
latest: Pulling from jjy0/riscv-qemu-fedora
171857c49d0f: Pull complete
419640447d26: Pull complete
61e52f862619: Pull complete
fda53f069f7e: Pull complete
51fc56fddf86: Pull complete
fdd95457d3eb: Extracting [==================================================>]  1.683GB/1.683GB
docker: failed to register layer: Error processing tar file(exit status 1): unexpected EOF.
See 'docker run --help'.
Makefile:52: recipe for target 'qemu' failed
make: *** [qemu] Error 125
~/jonesforth_riscv$

**Comment by jjyr** [comment]
Hi, I guess it is a docker registry error, please build the image yourself https://github.com/jjyr/docker-riscv-qemu-fedora

**Comment by Phi-Ho** [comment]
Hi,

Do you have any idea if this tar file may be broken with "unexpected EOF", would you verify it, please?
Thank you for sharing. It is much appreciated.

Regards,

phiho

**Comment by jjyr** [comment]
I have no idea, it is a docker registry bug, you can report this error to docker.

**Comment by Phi-Ho** [comment]
Hi,

You wrote:

>  I guess it is a docker registry error, please build the image yourself
https://github.com/jjyr/docker-riscv-qemu-fedora

I did this and the build went through successfully but ssh could not
connect:

~/docker-riscv-qemu-fedora$ ssh -p 1234 -o UserKnownHostsFile=/dev/null -o
StrictHostKeyChecking=no root@localhost
ssh: connect to host localhost port 1234: Connection refused
~/docker-riscv-qemu-fedora$

Did I miss something?

Regards,

phiho


....
....
....
2021-01-26 04:19:58 (4.32 MB/s) -
'Fedora-Developer-Rawhide-20190703.n.0-sda.raw.xz' saved
[1199376968/1199376968]

--2021-01-26 04:19:58--
https://dl.fedoraproject.org/pub/alt/risc-v/disk-images/fedora/rawhide/20190703.n.0/Developer/fw_payload-uboot-qemu-virt-smode.elf
Resolving dl.fedoraproject.org (dl.fedoraproject.org)... 38.145.60.24,
38.145.60.22, 38.145.60.23
Connecting to dl.fedoraproject.org (dl.fedoraproject.org)|38.145.60.24|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: 476536 (465K)
Saving to: 'fw_payload-uboot-qemu-virt-smode.elf'

     0K .......... .......... .......... .......... .......... 10%  729K 1s
    50K .......... .......... .......... .......... .......... 21% 2.18M 0s
   100K .......... .......... .......... .......... .......... 32% 5.37M 0s
   150K .......... .......... .......... .......... .......... 42% 2.52M 0s
   200K .......... .......... .......... .......... .......... 53% 2.65M 0s
   250K .......... .......... .......... .......... .......... 64% 10.4M 0s
   300K .......... .......... .......... .......... .......... 75% 10.9M 0s
   350K .......... .......... .......... .......... .......... 85% 2.23M 0s
   400K .......... .......... .......... .......... .......... 96% 4.67M 0s
   450K .......... .....                                      100%
25.0M=0.2s

2021-01-26 04:19:59 (2.53 MB/s) - 'fw_payload-uboot-qemu-virt-smode.elf'
saved [476536/476536]

Removing intermediate container 520e668835ea
 ---> fe2a0a6b26cc
Step 5/6 : EXPOSE 10000
 ---> Running in 6e1e1adaadac
Removing intermediate container 6e1e1adaadac
 ---> 2938c16b813a
Step 6/6 : CMD qemu-system-riscv64 -nographic -machine virt -smp 4 -m 2G
-kernel fw_payload-uboot-qemu-virt-smode.elf -device
virtio-blk-device,drive=hd0 -drive
file=Fedora-Developer-Rawhide-20190703.n.0-sda.raw,format=raw,id=hd0
-device virtio-net-device,netdev=usernet -netdev
user,id=usernet,hostfwd=tcp::10000-:22
 ---> Running in 4f4e8d88c665
Removing intermediate container 4f4e8d88c665
 ---> 7f033ca04fdf
Successfully built 7f033ca04fdf
Successfully tagged jjy0/riscv-qemu-fedora:latest
~/docker-riscv-qemu-fedora$

**Comment by jjyr** [comment]
> I did this and the build went through successfully but ssh could not
connect

I also sometimes went into this error, but I can't figure the issue. I guess it related to the lack of memory or some internal docker container issue. Usually, rebooting the machine fixes this problem.

I believe you can avoid this error via run qemu on Linux directly or run the code on the real hardware.
