### ISSUE TITLE
docker-riscv-qemu-fedora root password

### ISSUE THREAD

**Issue by Phi-Ho** [jjyr/jonesforth_riscv#4]
Hi,

You wrote:

>  I guess it is a docker registry error, please build the image yourself https://github.com/jjyr/docker-riscv-qemu-fedora

I did this and the build went through successfully but ssh could not connect:

~/docker-riscv-qemu-fedora$ ssh -p 1234 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost
ssh: connect to host localhost port 1234: Connection refused

I tried to connect with default port it look OK:

~/docker-riscv-qemu-fedora$ ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
root@localhost's password:

However, the password "riscv" was not accepted.

Please advise what is the correct root password?

Thank you for your help.

Regards,

phiho

**Comment by jjyr** [comment]
Are you sure you connect to the right host? I recommend running the qemu on Linux instead of run it in the docker.

Also, read the comment:
https://github.com/jjyr/jonesforth_riscv/issues/3#issuecomment-767306883

**Comment by Phi-Ho** [comment]
After rebooting:

~/jonesforth_riscv$ ssh -p 1234 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost
ssh: connect to host localhost port 1234: Connection refused

~/jonesforth_riscv$ ssh -p 4321 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@localhost
ssh: connect to host localhost port 4321: Connection refused

**Comment by Phi-Ho** [comment]
Hi,

> Are you sure you connect to the right host?

No, I was wrong, the default port connect to the real local host, NOT the local host in the docker. 
Sorry for the confusion.

Regards,

phiho
